/**
 * Represent a documentation of a release.
 * @constructor Create a Doc object.
 * @param {int} id - The id of the Doc. It is unique and is generated by the database.
 * @param {string} url - The URL of the documentation.
 * @param {int} releaseId - The id of the release to which this Doc object is linked to.
 */
class Doc {
  constructor(id, url, releaseId) {
    this.id = id
    this.url = url
    this.releaseId = releaseId
  }
}

/**
 * Export the Doc class so it can be used in other files.
 */
module.exports = {
  Doc: Doc
}
