/**
 * Represent an issue of a project.
 * @constructor Create an Issue object.
 * @param {int} id - The id of the issue. It is unique and is generated by the database.
 * @param {int} projectId - The id of the project the issue belongs to.
 * @param {string} name - The name of the issue.
 * @param {string} description - The description of the issue.
 * @param {string} priority - The priority of the issue. It should be "LOW", "MEDIUM" or "HIGH".
 * @param {int} difficulty - The difficulty of the issue. It should be an integer greater than 0.
 */
class Issue {
  constructor(id, projectId, name, description, priority, difficulty) {
    this.name = name
    this.description = description
    this.projectId = projectId
    this.id = id
    this.priority = priority
    this.difficulty = difficulty
  }
}

/**
 * Export the Issue class so it can be used in other files.
 */
module.exports = {
  Issue: Issue
}
