/**
 * Represent a project.
 * @constructor Create a Project object.
 * @param {int} id - The id of the project. It is unique and is generated by the database.
 * @param {string} name - The name of the project.
 * @param {string} description - The description of the project.
 * @param {Array} listMembers - The list of the Members taking part in the project.
 * @param {Array} listAdmins - The list of the administrators of the project. By default, it sould contains only the creator of the project.
 * @param {string} userGitHub - The username of the owner of the GitHub repository used for the releases of the project. By default, it should be "".
 * @param {string} repositoryGitHub - The name of the GitHub repository used for the releases of the project. By default, it should be "".
 */
class Project {
  constructor(
    id,
    name,
    description,
    listMembers,
    listAdmins,
    userGitHub,
    repositoryGitHub
  ) {
    this.name = name
    this.description = description
    this.id = id
    this.listMembers = listMembers
    this.listAdmins = listAdmins
    this.userGitHub = userGitHub
    this.repositoryGitHub = repositoryGitHub
  }
}

/**
 * Export the Project class so it can be used in other files.
 */
module.exports = {
  Project: Project
}
