/**
 * Represent an issue.
 * @constructor Create an Issue object.
 * @param {int} id - The id of the Issue object. It is generated by the database.
 * @param {int} projectId - The id of the project the Issue belongs to.
 * @param {string} name - The name of the Issue.
 * @param {string} description - The description of the Issue.
 * @param {string} priority - The priority of the Issue.
 * @param {int} difficulty - The difficulty of the Issue.
 */
class Sprint {
  constructor(
    id,
    project_id,
    objective,
    date_begin,
    date_end,
    listIssues,
    release
  ) {
    this.id = id
    this.project_id = project_id
    this.objective = objective
    this.date_begin = date_begin
    this.date_end = date_end
    this.listIssues = listIssues
    this.release = release
    this.taskToDo = []
    this.taskDoing = []
    this.taskDone = []
    this.numberOfTasks = 0
  }

  addTaskToDo(task) {
    this.taskToDo.push(task)
    this.numberOfTasks++
  }

  addTaskDoing(task) {
    this.taskDoing.push(task)
    this.numberOfTasks++
  }

  addTaskDone(task) {
    this.taskDone.push(task)
    this.numberOfTasks++
  }
}

/**
 * Export the Sprint class so it can be used in other files.
 */
module.exports = {
  Sprint: Sprint
}
