/**
 * Represent a task.
 * @constructor Create a Task object.
 * @param {int} id - The id of the task. It is generated by the database.
 * @param {int} projectId - The id of the project the task belongs to.
 * @param {string} name - The name of the task.
 * @param {string} description - The description of the task.
 * @param {string} state - The current state of the task. It should be "to do", "doing" or "done".
 * @param {date} start_date - The date the implementation of the task should start.
 * @param {int} realisation_time - The time in "jh" estimated to implement this task. It should be an integer greater or equal to 0.
 * @param {string} dod - The Definition of Done of the task.
 * @param {Array} dependancies - The list of tasks that need to be done before starting this one.
 * @param {Array} members - The members of the project assigned to this task.
 * @param {Array} issues - The list of issues this task implements.
 */
class Task {
  constructor(
    taskId,
    projectId,
    name,
    description,
    state,
    start_date,
    realisation_time,
    dod,
    dependancies,
    members,
    issues
  ) {
    this.taskId = taskId
    this.projectId = projectId
    this.name = name
    this.description = description
    this.state = state
    this.start_date = start_date
    this.realisation_time = realisation_time
    this.dod = dod
    this.members = members
    this.dependancies = dependancies
    this.issues = issues
  }
}

/**
 * Export the Task class so it can be used in other files.
 */
module.exports = {
  Task: Task
}
