/**
 * Represent an test.
 * @constructor Create an Test object.
 * @param {int} id - The id of the Test object. It is unique and is generated by the database.
 * @param {int} projectId - The id of the project the test belongs to.
 * @param {string} name - The name of the test.
 * @param {string} description - The description of the test.
 * @param {string} resultExpected - The results we should have if the test is passed.
 * @param {string} state - The current state of the test. It should be "todo", "passed" or "failed". By default, it should be "todo".
 * @param {Array} listIssues - The list of the issues taht should be implemented at the end of the sprint.
 */
class Test {
  constructor(
    id,
    projectId,
    name,
    description,
    resultExpected,
    lastVersionValidated,
    state,
    listIssues
  ) {
    this.name = name
    this.description = description
    this.projectId = projectId
    this.id = id
    this.resultExpected = resultExpected
    this.lastVersionValidated = lastVersionValidated
    this.state = state
    this.listIssues = listIssues
  }
}

/**
 * Export the Test class so it can be used in other files.
 */
module.exports = {
  Test: Test
}
