// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('indexWithoutSession', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('indexWithoutSession', async function() {
    await driver.get("http://localhost:3000/")
    await driver.setRect(1251, 727)
    await driver.findElement(By.css(".jumbotron")).click()
  })
})
