// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('listProjects', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('listProjects', async function() {
    await driver.get("http://localhost:3000/")
    await driver.setRect(1251, 722)
    await driver.findElement(By.linkText("Manage Projects")).click()
  })
})
