// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('removeTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('removeTest', async function() {
    await driver.get("http://localhost:3000/")
    await driver.setRect(1251, 725)
    await driver.findElement(By.css(".btn-outline-success")).click()
    await driver.findElement(By.id("dropdownMenuButton")).click()
    await driver.findElement(By.linkText("Bonjour")).click()
    await driver.findElement(By.linkText("Tests")).click()
    await driver.findElement(By.linkText("15: Test1 modified")).click()
    await driver.findElement(By.css("#collapse15 form > .btn")).click()
    assert(await driver.switchTo().alert().getText() == "Voulez-vous vraiment supprimer ce test ?")
    await driver.switchTo().alert().accept()
  })
})
