// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('003_usernameAlreadyUsed', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit()
  })
  it('003_usernameAlreadyUsed', async function() {
    await driver.get('http://localhost:3000/')
    await driver.findElement(By.linkText('Sign Up')).click()
    await driver.findElement(By.id('username')).sendKeys('Test')
    await driver.findElement(By.css('.card-header')).click()
    await driver.findElement(By.id('password')).click()
    await driver.findElement(By.id('password')).sendKeys('test2')
    await driver.findElement(By.id('confirmedPassword')).click()
    await driver.findElement(By.id('confirmedPassword')).sendKeys('test2')
    await driver.findElement(By.css('.btn-primary')).click()
  })
})
