// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('008_addTaskThenModifyTaskThenDeleteTask', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('008_addTaskThenModifyTaskThenDeleteTask', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("Test")
    await driver.findElement(By.css(".card-body")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("test")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("Details")).click()
    await driver.findElement(By.css(".nav-link:nth-child(2) > .pl-3")).click()
    await driver.findElement(By.linkText("Add new task")).click()
    {
      const element = await driver.findElement(By.id("taskName"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("taskName"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("taskName"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Task 1")
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Ceci est la task 1")
    await driver.findElement(By.id("taskState1")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-12-18")
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("2")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDuration")).sendKeys("3")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("4")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Done")
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'User5']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I2']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("Add new task")).click()
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Task2")
    await driver.findElement(By.css(".card-body > .form-group:nth-child(1)")).click()
    await driver.findElement(By.id("taskDescription")).click()
    await driver.findElement(By.id("taskDescription")).sendKeys("Ceci est la task2")
    await driver.findElement(By.css(".form-check:nth-child(4)")).click()
    await driver.findElement(By.id("taskState3")).click()
    await driver.findElement(By.id("startDate")).click()
    await driver.findElement(By.id("startDate")).sendKeys("2019-12-11")
    await driver.findElement(By.id("taskDuration")).sendKeys("1")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("2")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDuration")).sendKeys("3")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDuration")).sendKeys("4")
    await driver.findElement(By.id("taskDuration")).click()
    {
      const element = await driver.findElement(By.id("taskDuration"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("taskDuration")).sendKeys("5")
    await driver.findElement(By.id("taskDuration")).click()
    await driver.findElement(By.id("taskDoD")).click()
    await driver.findElement(By.id("taskDoD")).sendKeys("Done")
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'User5']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskMember"))
      await dropdown.findElement(By.xpath("//option[. = 'Test']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskRequired"))
      await dropdown.findElement(By.xpath("//option[. = 'Task 1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("taskIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I2']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_done .mb-1")).click()
    {
      const element = await driver.findElement(By.css("#tasks_done .mb-1"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Modify")).click()
    await driver.findElement(By.id("taskName")).click()
    await driver.findElement(By.id("taskName")).sendKeys("Task2 bis")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.css("#tasks_done .mb-1")).click()
    await driver.findElement(By.xpath("(//button[@type=\'submit\'])[4]")).click()
    await driver.findElement(By.name("signout")).click()
  })
})
