// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('012_addSprintToReleaseThenModifySprintOfRelease', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('012_addSprintToReleaseThenModifySprintOfRelease', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("Test")
    await driver.findElement(By.css(".form-group:nth-child(3)")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("test")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("Details")).click()
    await driver.findElement(By.css(".nav-link:nth-child(3) > .pl-3")).click()
    await driver.findElement(By.linkText("Add Sprint")).click()
    await driver.findElement(By.id("sprintObjective")).click()
    await driver.findElement(By.id("sprintObjective")).sendKeys("Ca marche")
    {
      const dropdown = await driver.findElement(By.id("sprintIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    {
      const dropdown = await driver.findElement(By.id("sprintIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I2']")).click()
    }
    await driver.findElement(By.id("date_begin")).click()
    await driver.findElement(By.id("date_begin")).sendKeys("2019-12-25")
    await driver.findElement(By.id("date_end")).click()
    await driver.findElement(By.id("date_end")).sendKeys("2019-12-25")
    await driver.findElement(By.xpath("(//button[@type=\'submit\'])[3]")).click()
    await driver.findElement(By.linkText("Add Sprint")).click()
    await driver.findElement(By.id("sprintObjective")).click()
    await driver.findElement(By.id("sprintObjective")).sendKeys("Ca marche 2")
    {
      const dropdown = await driver.findElement(By.id("sprintIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I1']")).click()
    }
    await driver.findElement(By.css("option:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css("option:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    {
      const dropdown = await driver.findElement(By.id("sprintIssue"))
      await dropdown.findElement(By.xpath("//option[. = 'I2']")).click()
    }
    await driver.findElement(By.id("date_begin")).click()
    await driver.findElement(By.id("date_begin")).sendKeys("2019-12-27")
    await driver.findElement(By.id("date_end")).click()
    await driver.findElement(By.id("date_end")).sendKeys("2019-12-26")
    await driver.findElement(By.css(".float-right:nth-child(1)")).click()
    await driver.findElement(By.css(".nav-link:nth-child(4) > .pl-3")).click()
    await driver.findElement(By.css("#heading21773215 .badge")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.css(".list-inline-item:nth-child(1) .form-check-label")).click()
    await driver.findElement(By.id("modifySprintOfRelease")).click()
    await driver.findElement(By.css("#heading21773215 .badge")).click()
    await driver.findElement(By.linkText("✎")).click()
    await driver.findElement(By.css(".list-inline-item:nth-child(2) > .form-check")).click()
    await driver.findElement(By.xpath("//ul[@id=\'listSprints\']/li[2]/div/input")).click()
    await driver.findElement(By.id("modifySprintOfRelease")).click()
    await driver.findElement(By.name("signout")).click()
  })
})
