// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('013_modifyProjectSettingsAsAdmin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('013_modifyProjectSettingsAsAdmin', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.id("username")).sendKeys("Test")
    await driver.findElement(By.css(".form-group:nth-child(2)")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("test")
    await driver.findElement(By.css(".btn-primary")).click()
    await driver.findElement(By.linkText("Details")).click()
    await driver.findElement(By.css(".nav-link:nth-child(6) > .pl-3")).click()
    await driver.findElement(By.id("projectName")).click()
    await driver.findElement(By.id("projectName")).sendKeys("Project for tests")
    await driver.findElement(By.id("createNewProject")).click()
    await driver.findElement(By.name("signout")).click()
  })
})
