// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class AddLotsOfWeirdIssuesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addLotsOfWeirdIssues() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1251, 722));
    driver.findElement(By.linkText("Sign In")).click();
    driver.findElement(By.id("username")).sendKeys("coucou");
    driver.findElement(By.id("password")).sendKeys("h");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("li:nth-child(2) .list-inline-item > .btn")).click();
    driver.findElement(By.linkText("Issues")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("I1");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("LOW");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("i1");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("I2");
    driver.findElement(By.id("headingAddIssue")).click();
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("0");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-1");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-2");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-3");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issuePriority")).sendKeys("HIGH");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("Bonjour");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("I4");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("6");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("7");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("8");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("9");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("10");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("11");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("12");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("13");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("14");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("15");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("16");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("17");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("18");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("19");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("20");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("21");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("22");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("23");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("24");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("25");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("26");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("27");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("28");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("29");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("30");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("31");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("32");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("33");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("34");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("35");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("MEDIUM");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("High difficulty");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("gjckjsvcuzqdjxiaqeoudjeoùz^f duevg4r6z8\'gmrihgrziof4sfresgh");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("LOW");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("strange name");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("Strange description");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("nfioezhfez#mofjoierjf56853258fnlekzjfgzuhfnfe4r6z4f5e64f8zr4fsz4fznjzehuifeè_-{}[]()%BGFHMOOYbffhb");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("LOW");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("Strange name 2");
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("#\"[]{(})%;?!ùmjkpohozef185.fe63tez57grnljgzjpané&hk,fs_-=°njk");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("6");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issuePriority")).sendKeys("HIGH");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("Strang name3");
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("é#{([])}+--_?;!|ù%è");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issuePriority")).sendKeys("LOW");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("123646898798597987899856568979878979798798746451312315646*/-+");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("0");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-6");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-7");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-8");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-9");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-10");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-11");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-12");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-13");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-14");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-15");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-16");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-17");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-18");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-19");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-20");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-21");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-22");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-23");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-24");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-25");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("medium");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("Strange name again");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Issues")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("123456779952599562");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("Many numbers");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-6");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-7");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-8");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-9");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-10");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issuePriority")).sendKeys("medium");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("abcdefghijklmnopqrstuvwxyzABCDJPÖHUJH");
    driver.findElement(By.id("headingAddIssue")).click();
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("0");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-1");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-2");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-3");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-4");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-5");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-6");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-7");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-8");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-9");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-10");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-11");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-12");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-13");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-14");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-15");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-16");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-17");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-18");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-19");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-20");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-21");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-22");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("-23");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("-24");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("medium");
    driver.findElement(By.cssSelector("#collapseAddIssue .list-group-item:nth-child(1)")).click();
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("hyjutrz");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.id("issueName")).sendKeys("{(]-_|}[)");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("{(]-_|}[)");
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("2");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("3");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("4");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("5");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("6");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("7");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("8");
    driver.findElement(By.id("issueDifficulty")).click();
    {
      WebElement element = driver.findElement(By.id("issueDifficulty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("issueDifficulty")).sendKeys("9");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("{(]-_|}[)");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
  }
}
