// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CreateNewProjectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createNewProject() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1251, 722));
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.linkText("New Project")).click();
    driver.findElement(By.id("projectName")).click();
    driver.findElement(By.id("projectName")).sendKeys("ProjectTest");
    driver.findElement(By.id("projectDescription")).click();
    driver.findElement(By.id("projectDescription")).sendKeys("Project to test the appli");
    driver.findElement(By.id("usernameMemberToAdd")).click();
    driver.findElement(By.id("usernameMemberToAdd")).sendKeys("User5");
    driver.findElement(By.cssSelector(".btn:nth-child(6)")).click();
    driver.findElement(By.id("projectName")).click();
    driver.findElement(By.id("projectName")).sendKeys("Project ");
    driver.findElement(By.id("projectName")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("projectName")).sendKeys("ProjectTest");
    driver.findElement(By.id("projectDescription")).click();
    driver.findElement(By.id("projectDescription")).sendKeys("P");
    driver.findElement(By.id("projectDescription")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("projectDescription")).sendKeys("Project to test the appli");
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("usernameMemberToAdd")).click();
    driver.findElement(By.id("usernameMemberToAdd")).sendKeys("User5");
    driver.findElement(By.cssSelector(".btn:nth-child(6)")).click();
    driver.findElement(By.id("projectName")).click();
    driver.findElement(By.id("projectName")).sendKeys("P");
    driver.findElement(By.id("projectName")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("projectName")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("projectName")).sendKeys("ProjectTest");
    driver.findElement(By.id("projectDescription")).click();
    driver.findElement(By.id("projectDescription")).sendKeys("Pro");
    driver.findElement(By.id("projectDescription")).sendKeys(Keys.DOWN);
    driver.findElement(By.id("projectDescription")).sendKeys("Project to test the appli");
    driver.findElement(By.id("createNewProject")).click();
  }
}
