// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class ModifyIssueBugDifficultyStringTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modifyIssueBugDifficultyString() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1251, 722));
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) .list-inline-item > .btn")).click();
    driver.findElement(By.linkText("Issues")).click();
    driver.findElement(By.cssSelector("#heading136 > .d-block")).click();
    driver.findElement(By.linkText("✎")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("I1 renamed");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("#heading137 .badge-danger")).click();
    driver.findElement(By.linkText("✎")).click();
    driver.findElement(By.name("issueDescription")).click();
    driver.findElement(By.name("issueDescription")).sendKeys("Test2 new description");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".badge-warning")).click();
    driver.findElement(By.linkText("✎")).click();
    driver.findElement(By.name("issuePriority")).click();
    driver.findElement(By.name("issuePriority")).sendKeys("LOW");
    driver.findElement(By.cssSelector(".px-4")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("#heading139 > .d-block")).click();
    driver.findElement(By.linkText("✎")).click();
    driver.findElement(By.name("issueDifficulty")).click();
    driver.findElement(By.name("issueDifficulty")).click();
    driver.findElement(By.name("issueDifficulty")).sendKeys("3");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("#heading140 > .d-block")).click();
    driver.findElement(By.linkText("✎")).click();
    driver.findElement(By.name("issueDifficulty")).click();
    driver.findElement(By.name("issueDifficulty")).sendKeys("abcd");
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
