// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class RemoveIssueAndAddIssueTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void removeIssueAndAddIssue() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1251, 722));
    driver.findElement(By.linkText("Manage Projects")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) .list-inline-item > .btn")).click();
    driver.findElement(By.linkText("Issues")).click();
    driver.findElement(By.cssSelector("#heading137 .badge-danger")).click();
    driver.findElement(By.cssSelector("#collapse137 form > .btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Voulez-vous vraiment supprimer cette issue ?"));
    driver.switchTo().alert().accept();
    driver.findElement(By.linkText("Add Issue")).click();
    driver.findElement(By.id("issueName")).click();
    driver.findElement(By.id("issueName")).sendKeys("I2 new");
    driver.findElement(By.cssSelector(".badge:nth-child(5)")).click();
    driver.findElement(By.id("issuePriority")).click();
    driver.findElement(By.id("issuePriority")).sendKeys("LOW");
    driver.findElement(By.id("issueDifficulty")).click();
    driver.findElement(By.id("issueDifficulty")).sendKeys("1");
    driver.findElement(By.id("issueDescription")).click();
    driver.findElement(By.id("issueDescription")).sendKeys("I2 revived!");
    driver.findElement(By.cssSelector(".float-right:nth-child(1)")).click();
    driver.findElement(By.cssSelector("#heading143 > .d-block")).click();
    driver.findElement(By.cssSelector("#collapse143 form > .btn")).click();
    assertThat(driver.switchTo().alert().getText(), is("Voulez-vous vraiment supprimer cette issue ?"));
    driver.switchTo().alert().accept();
  }
}
